# Generated by Django 2.0.5 on 2018-05-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPayOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_nums', models.IntegerField(default=1, verbose_name='回报数量')),
                ('freight', models.IntegerField(default=0, verbose_name='配送费用')),
                ('coupon', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='优惠金额')),
                ('total_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总金额')),
                ('need_invoice', models.BooleanField(default=False, verbose_name='是否开票')),
                ('info_invoice', models.CharField(default='个人', max_length=100, verbose_name='发票抬头')),
                ('remarks', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注信息')),
                ('order_time', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('pay_time', models.DateTimeField(auto_now_add=True, verbose_name='支付时间')),
                ('order_no', models.CharField(default='', max_length=100, verbose_name='订单编号')),
                ('pay_order_no', models.CharField(default='', max_length=100, verbose_name='付款单号')),
                ('order_status', models.CharField(choices=[('waiting', '待支付'), ('paid', '已支付'), ('closed', '订单关闭'), ('completed', '已完成')], default='waiting', max_length=20, verbose_name='订单状态')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
            },
        ),
    ]
