# Generated by Django 2.0.5 on 2018-05-15 19:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='admin',
            field=models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL, verbose_name='管理用户'),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete='CASCADE', to='projects.ProjectCategory', verbose_name='项目类别'),
        ),
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(on_delete='CASCADE', to='projects.Company', verbose_name='企业名称'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ForeignKey(on_delete='CASCADE', to='projects.ProjectTags', verbose_name='项目标签'),
        ),
        migrations.AddField(
            model_name='company',
            name='admin',
            field=models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL, verbose_name='管理用户'),
        ),
    ]
