# Generated by Django 2.0.5 on 2018-05-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersupport',
            name='item',
            field=models.ForeignKey(on_delete='CASCADE', to='projects.ProjectItem', verbose_name='回报名称'),
        ),
        migrations.AddField(
            model_name='usersupport',
            name='project',
            field=models.ForeignKey(on_delete='CASCADE', to='projects.Project', verbose_name='项目名称'),
        ),
    ]
