# Generated by Django 2.0.5 on 2018-05-15 19:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0002_auto_20180515_1921'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usersupport',
            name='user',
            field=models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='userinterest',
            name='project',
            field=models.ForeignKey(on_delete='CASCADE', to='projects.Project', verbose_name='关注企业'),
        ),
        migrations.AddField(
            model_name='userinterest',
            name='user',
            field=models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_project',
            field=models.ForeignKey(on_delete='cascade', to='projects.Project', verbose_name='众筹项目'),
        ),
        migrations.AddField(
            model_name='advertise',
            name='project',
            field=models.ForeignKey(on_delete='cascade', to='projects.Project', verbose_name='项目'),
        ),
    ]
